### PR TITLE
switch: Add touch input support

### PR DESCRIPTION
**Pull request by bylaws**
Emulates mouse inputs using touch

### CODE REVIEW

**Comment by fincs** [comment]
Thank you for your contribution. A few comments:

- I wouldn't have moved the location of the `hidScanInput` call in order to be able to place the mouse emulation code in `_glfwPlatformPollEvents`; I would have just added the mouse emulation code to the end of `_glfwUpdateSwitchJoysticks` directly.
- I think you should only send a `GLFW_PRESS` message if the "mouse" button wasn't already pressed, otherwise glfw could misunderstand mouse drags as repeated clicks.
- Touch position always use 1280x720 coordinates; they should be scaled to the window dimensions.

**Comment by bylaws** [comment]
Thanks for the feedback,
I think i addressed all the issues you mentioned, though i didn't test having any other window sizes it should still work.

**Comment by bylaws** [comment]
@fincs

**Comment by hippydave** [comment]
This would be useful, any thoughts?

**Comment by jakibaki** [comment]
Any update on this?

**Comment by bylaws** [comment]
Hello, this has been pending for a really long time and would be really useful, can you review?

**Comment by natinusala** [comment]
I work on a project that could also use this feature, thanks :+1:

**Comment by fincs** [comment]
Patience please. We are in the middle of sorting out important libnx changes right now.

**Comment by natinusala** [comment]
I hate to insist but is there any news on this?

**Comment by bylaws** [comment]
`any news?`

**Comment by bylaws** [comment]
Amy updates on this?

**Comment by bylaws** [comment]
Would love for this to be merged @fincs @devkitpro

**Comment by bylaws** [comment]
Hello?

**Comment by bylaws** [comment]
can someone merge

**Comment by bylaws** [comment]
would be brilliant if this could be merged @fincs

**Comment by fincs** [comment]
@bylaws Bumping this PR over and over isn't really going to make us merge it any faster, in fact I'd argue it will have the opposite effect.

We're almost always busy working on other stuff that has higher priority (such as toolchain/libnx releases and whatnot), and there's a really huge shake-up of the way to do 3D graphics on Switch homebrew coming up soon. We'll get to it when we get to it.

**Pull request merged**
